---
- name: Upgrade grub
  ansible.builtin.command: update-grub

- name: Reboot
  ansible.builtin.reboot:
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
