---
- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- ansible.builtin.import_tasks: "packages.yml"

- ansible.builtin.include_tasks: "sysctl.yml"

- ansible.builtin.include_tasks: "hardening.yml"

- name: Disable ssh password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify: Restart sshd

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  notify: Reboot
