---
- name: Restart cron
  ansible.builtin.systemd:
    name: cron
    state: restarted

- name: Reboot
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
